version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  zubbi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # flask runs on port 5000 per default
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - esnet
    # We need to "wait" until Elasticsearch is up and running
    restart: always

volumes:
  esdata:
    driver: local

networks:
  esnet:
